# 1. 生成数据集
这个跟之前的方法一样。

In [29]:
import numpy as np 
import torch
from torch.utils import data 
from d2l import torch as d2l

In [30]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

# 2. 读取数据集
这里用torch提供的方法。
有点和官方文档不那么搭，但可以凑合看先后面再熟练。

In [31]:
def load_array(data_arrays, batch_size, is_train=True):
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

In [32]:
batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [33]:
next(iter(data_iter))

[tensor([[ 2.0663, -0.4319],
         [-0.5445, -1.9487],
         [-0.8473,  1.6369],
         [ 0.6440,  1.3397],
         [-0.7722,  0.7289],
         [ 1.7517, -0.4381],
         [ 2.0527,  1.3326],
         [ 1.4140, -0.8294],
         [ 1.0217, -1.2596],
         [ 1.4865,  0.3355]]),
 tensor([[ 9.8015],
         [ 9.7378],
         [-3.0596],
         [ 0.9306],
         [ 0.1719],
         [ 9.1809],
         [ 3.7881],
         [ 9.8692],
         [10.5274],
         [ 6.0341]])]

In [34]:
data_iter

# 3.定义模型

In [35]:
# 这里可能也写的比较随意
# 没有写成一个class 后面再看吧！
from torch import nn

net = nn.Sequential(nn.Linear(2, 1))

# 4. 初始化模型参数

In [36]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

# 5. 定义损失函数

In [37]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

In [38]:
list(net.parameters())

[Parameter containing:
 tensor([[0.0048, 0.0118]], requires_grad=True),
 Parameter containing:
 tensor([0.], requires_grad=True)]

# 6. 训练

In [42]:
# 漏掉了 忘记loss了
loss = torch.nn.MSELoss() #注意这里和之前的不一样  1
# loss = torch.nn.MSELoss 这个是错的 2
# 1写法是torch里面的，就是MSELoss是一个类，后面类似函数的调用会调用他的forward
# 自定义model class也会这样
# 2 写法是我原本写了一个函数 赋值给另一个变量

num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X), y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch: {epoch + 1}, loss: {l:f}')

epoch: 1, loss: 0.000340
epoch: 2, loss: 0.000096
epoch: 3, loss: 0.000096


In [40]:
torch.nn.MSELoss

torch.nn.modules.loss.MSELoss

In [41]:
torch.nn.MSELoss()

MSELoss()